spring.application.name=zebrih


# Přepne JSF do vývojového režimu (vypne cache šablon)
jakarta.faces.PROJECT_STAGE=Development
joinfaces.jsf.project-stage=Development

# Vypne ukládání stavu na serveru pro rychlejší reload
jakarta.faces.FACELETS_REFRESH_PERIOD=0


server.address=0.0.0.0